language: ruby
cache: bundler
bundler_args: --without system_tests development
script: "bundle exec rake validate && bundle exec rake test SPEC_OPTS='--format documentation'"
sudo: false
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 4.0"
  allow_failures:
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
notifications:
  email: false
  hipchat:
    rooms:
      - secure: "QkHFNE9oBJXW9SEXHtw+ekvApwxZjdsKAL2O+NEw80raURmw5QB4Na0AGJ98WnWspfiSzS56yLYiC7cQyPA3XQW4RME+kBpOfYLUZ59eOfpguk5XMgWLSKhDTlPGFLiRpqgYXZmOUG2cWpN6qIWbCGxN3gf0/YHmopqdhDq8zkY="
  on_success: always
  on_failure: always
